[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "src/functions"
  node_bundler = "esbuild"




